
const data = [
    {
        "id": 1,
        "post": "Baking Alley",
        "description": "Get all your baking essentials at one stop. We deal in all types of baking raw materials, equipments and decoration items.",
        "link": "https://www.instagram.com/p/CTeR07yspNU/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID1.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "06-09-2021"
    },
    {
        "id": 2,
        "post": "Invest Energy",
        "description": "Do share if you like.",
        "link": "https://www.instagram.com/p/CTg07yrsZPl/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID2.JPG").default,
        "insta_handle": "invest.energy",
        "date": "07-09-2021"
    },
    {
        "id": 3,
        "post": "Baking Alley",
        "description": "DUMMY ALCOHOL BOTTLES DM FOR PRICES",
        "link": "https://www.instagram.com/p/CVKitPdNa0C/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID3.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "18-10-2021"
    },
    {
        "id": 4,
        "post": "Invest Energy",
        "description": "Solar power now offers the cheapest way to generate electricity in history, and is considerably more affordable than power generated by coal or gas in most major countries.",
        "link": "https://www.instagram.com/p/CUKcUFjtGGD/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID4.JPG").default,
        "insta_handle": "invest.energy",
        "date": "23-09-2021"
    },
    {
        "id": 5,
        "post": "Baking Alley",
        "description": "Flavoured Glaze",
        "link": "https://www.instagram.com/p/CUNDGQ4tnTo/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID5.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "24-09-2021"
    },
    {
        "id": 6,
        "post": "Invest Energy",
        "description": "It’s the climate crisis, it’s here, and it’s only getting worse. This is why we need real action NOW.Go to the link in our bio(www.investenergy.in) or message us to get a free consultation of best suitable Solar System for your home.This is the moment to go big on climate! ?? Switch to solar now!",
        "link": "https://www.instagram.com/p/CUsFidatkV-/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID6.JPG").default,
        "insta_handle": "invest.energy",
        "date": "06-10-2021"
    },
    {
        "id": 7,
        "post": "Baking Alley",
        "description": "BISCOFF BISCUIT AND SPREAD DM for prices",
        "link": "https://www.instagram.com/p/CUoxS4ytGsu/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID7.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "05-10-2021"
    },
    {
        "id": 8,
        "post": "Invest Energy",
        "description": "It’s the climate crisis, it’s here, and it’s only getting worse. This is why we need real action NOW.Go to the link in our bio(www.investenergy.in) or message us to get a free consultation of best suitable Solar System for your home.This is the moment to go big on climate! ?? Switch to solar now!",
        "link": "https://www.instagram.com/p/CU2ziGMNmcO/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID8.JPG").default,
        "insta_handle": "invest.energy",
        "date": "10-10-2021"
    },
    {
        "id": 9,
        "post": "Baking Alley",
        "description": "DIWALI PVC MOULDS AVAILABLE DM FOR PRICES",
        "link": "https://www.instagram.com/p/CVAPiBPNjbf/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID9.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "14-10-2021"
    },
    {
        "id": 10,
        "post": "Invest Energy",
        "description": "We can’t wait for a second longer. ? If you agree, go to the link in our bio and drop a query or dm us to get a free estimation for the best quality Solar System.",
        "link": "https://www.instagram.com/p/CUe45xrtriE/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID10.JPG").default,
        "insta_handle": "invest.energy",
        "date": "01-10-2021"
    },

    {
        "id": 11,
        "post": "Baking Alley",
        "description": "Avoid moisture loss and add varied tastes and attractive appearance to your cake using NEUTRAL GLAZE Brands Available: Vizyon, Rick, Cielo DM for price",
        "link": "https://www.instagram.com/p/CR_OYesLoKr/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID11.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "31-07-2021"
    },
    {
        "id": 12,
        "post": "Invest Energy",
        "description": "Visit our website for Estimation of installing Solar Electricity system at your home. investenergy.in / ",
        "link": "https://www.instagram.com/p/CUM-QG-NMwo/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID12.JPG").default,
        "insta_handle": "invest.energy",
        "date": "24-09-2021"
    },
    {
        "id": 13,
        "post": "Jersey Hub",
        "description": "Chelsea Retro Kits available ? DM to order ?? ",
        "link": "https://www.instagram.com/p/COFcKyvFPzr/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID13.JPG").default,
        "insta_handle": "_thejerseyhub_",
        "date": "25-04-2021"
    },
    {
        "id": 14,
        "post": "Invest Energy",
        "description": "This is why we need real action NOW. Go to the link in our bio(www.investenergy.in) or message us to get a free consultation of best suitable Solar System for your home. This is the moment to go big on climate! ?? Switch to solar now!",
        "link": "https://www.instagram.com/p/CVSH1lVtzN0/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID14.JPG").default,
        "insta_handle": "invest.energy",
        "date": "21-10-2021"
    },
    {
        "id": 15,
        "post": "Baking Alley",
        "description": "CHOCOLATE PACKING BOXES AND SMALL BAGS AVAILABLE DM FOR PRICES",
        "link": "https://www.instagram.com/p/CVfY0wfNVAQ/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID15.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "26-10-2021"
    },
    {
        "id": 16,
        "post": "Invest Energy",
        "description": "We want to share some of the reasons #WhySolar is the future. Solar is infinite, versatile, inexpensive and fair, plus it has a huge potential to grow economies around the globe. Does a renewable energy system seem like a distant dream ? It shouldn't be. We have the chance to operate on 70% solar power by 2030*. What we need is: You.",
        "link": "https://www.instagram.com/p/CUuuYadNOL7/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID16.JPG").default,
        "insta_handle": "invest.energy",
        "date": "07-10-2021"
    },
    {
        "id": 17,
        "post": "Baking Alley",
        "description": "SURPRISE CAKE BOMB AVAILABLE DM for price",
        "link": "https://www.instagram.com/p/CUUvmFQtuTE/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID17.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "27-09-2021"
    },
    {
        "id": 18,
        "post": "Invest Energy",
        "description": "People born today will suffer many times more extreme heatwaves and other climate disasters over their lifetimes than their grandparents, research has shown.",
        "link": "https://www.instagram.com/p/CUmUzxNt40Y/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID18.JPG").default,
        "insta_handle": "invest.energy",
        "date": "04-10-2021"
    },
    {
        "id": 19,
        "post": "Baking Alley",
        "description": "DIWALI STICKERS AVAILABLE LIMITED STOCK!! HURRY UP!! DM FOR PRICES",
        "link": "https://www.instagram.com/p/CVVd0iHtqXn/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID19.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "23-10-2021"
    },
    {
        "id": 20,
        "post": "Ifix Service",
        "description": "",
        "link": "https://www.instagram.com/p/CNumEFZnicJ/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID20.JPG").default,
        "insta_handle": "ifixservices5",
        "date": "16-04-2021"
    },
    {
        "id": 21,
        "post": "Baking Alley",
        "description": "PARTY POPPERS AVAILABLE DM for prices",
        "link": "https://www.instagram.com/p/CT666GQLF7O/?utm_source=ig_web_copy_link",
        "image": require("./post_imgs/ID21.JPG").default,
        "insta_handle": "baking_alley4",
        "date": "17-09-2021"
    }
]

export default data;